// Dữ liệu mẫu chuẩn hóa tỉnh Gia Lai với 100% hình ảnh thực tế

export const MOCK_LOCATIONS = [
  {
    "id": "LOC_BIENHO",
    "locationId": "LOC_BIENHO",
    "name": "Biển Hồ T'Nưng (Hồ Ea Nueng)",
    "address": "Xã Biển Hồ, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.0506,
    "lat": 14.0506,
    "longitude": 108.0001,
    "lng": 108.0001,
    "budget": 20000,
    "ticketPrice": 20000,
    "ratingAvg": 4.9,
    "avgRating": 4.9,
    "reviewCount": 18,
    "bestTime": "Sáng sớm hoặc Hoàng hôn",
    "bestTimeOfDay": "Sáng sớm hoặc Hoàng hôn",
    "imageUrl": "https://cdn.xanhsm.com/2025/03/8d98d60d-bien-ho-pleiku-13.jpg",
    "imageUrls": [
      "https://cdn.xanhsm.com/2025/03/8d98d60d-bien-ho-pleiku-13.jpg",
      "https://123didulich.com/wp-content/uploads/2021/03/bien-ho-pleiku-gia-lai-11.jpg",
      "https://ik.imagekit.io/tvlk/blog/2021/09/kinh-nghiem-du-lich-pleiku-4.jpg?tr=dpr-2,w-675"
    ],
    "description": "Đôi mắt Pleiku - Miệng núi lửa cổ bazan triệu năm với mặt nước biếc phẳng lặng như gương soi mây trời cao nguyên. Thắng cảnh quốc gia tiêu biểu nhất của tỉnh Gia Lai."
  },
  {
    "id": "LOC_CHUDANGYA",
    "locationId": "LOC_CHUDANGYA",
    "name": "Núi lửa Chư Đang Ya",
    "address": "Làng Ploi lagri, Xã Chư Đang Ya, Huyện Chư Păh, Gia Lai",
    "districtId": "D_CHUPAH",
    "district": "Huyện Chư Păh",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.15,
    "lat": 14.15,
    "longitude": 108.0667,
    "lng": 108.0667,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.9,
    "avgRating": 4.9,
    "reviewCount": 18,
    "bestTime": "Sáng sớm (mùa hoa dã quỳ tháng 10-12)",
    "bestTimeOfDay": "Sáng sớm (mùa hoa dã quỳ tháng 10-12)",
    "imageUrl": "https://gialai.info/wp-content/uploads/2023/02/anh-3-3-3135.jpg",
    "imageUrls": [
      "https://gialai.info/wp-content/uploads/2023/02/anh-3-3-3135.jpg",
      "https://cdnmedia.baotintuc.vn/Upload/3qVxwVtNEPp6Wp9kkF77g/files/2020/11/20/da-quy-201120-2.jpg",
      "https://www.dulichhaidang.com/uploads/contents/gioi-thieu-ve-nui-lua-chu-dang-ya_1702121165.jpg"
    ],
    "description": "Tuyệt tác miệng núi lửa cổ hình phễu lòng chảo triệu năm, nơi sắc vàng rực rỡ của hoa dã quỳ nở rộ khắp các triền bazan đỏ màu mỡ vào mỗi dịp cuối thu đầu đông."
  },
  {
    "id": "LOC_BIENHOCHE",
    "locationId": "LOC_BIENHOCHE",
    "name": "Biển Hồ Chè & Hàng thông trăm tuổi",
    "address": "Xã Nghĩa Hưng, Huyện Chư Păh, Gia Lai",
    "districtId": "D_CHUPAH",
    "district": "Huyện Chư Păh",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.075,
    "lat": 14.075,
    "longitude": 108.02,
    "lng": 108.02,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.8,
    "avgRating": 4.8,
    "reviewCount": 18,
    "bestTime": "Bình minh hoặc Chiều tà",
    "bestTimeOfDay": "Bình minh hoặc Chiều tà",
    "imageUrl": "https://static.riviu.co/image/2022/12/18/b104c97c2f6b1f0aef14c3d82fb24982_output.jpeg",
    "imageUrls": [
      "https://static.riviu.co/image/2022/12/18/b104c97c2f6b1f0aef14c3d82fb24982_output.jpeg",
      "https://static.riviu.co/image/2022/12/18/082449f09a67e0e3cd9757106c9fbde2_output.jpeg"
    ],
    "description": "Đồn điền chè đầu tiên của người Pháp tại Tây Nguyên (1919) trải dài tít tắp, kết hợp con đường hàng thông cổ thụ hơn 100 tuổi thơ mộng ngỡ như xứ sở kim chi."
  },
  {
    "id": "LOC_THACPHUCUONG",
    "locationId": "LOC_THACPHUCUONG",
    "name": "Thác Phú Cường",
    "address": "Xã Dun, Huyện Chư Sê, Gia Lai",
    "districtId": "D_CHUSE",
    "district": "Huyện Chư Sê",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 13.6822,
    "lat": 13.6822,
    "longitude": 108.1256,
    "lng": 108.1256,
    "budget": 25000,
    "ticketPrice": 25000,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Sáng 8h - 11h ngắm cầu vồng nước",
    "bestTimeOfDay": "Sáng 8h - 11h ngắm cầu vồng nước",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/thac-phu-cuong-chiem-nguong-tuyet-tac-cua-nui-rung-gia-lai-04-1659179228.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/thac-phu-cuong-chiem-nguong-tuyet-tac-cua-nui-rung-gia-lai-04-1659179228.jpg",
      "https://tintucgialai.com/wp-content/uploads/2023/05/anh-dai-dien-thac-phu-cuong.jpg"
    ],
    "description": "Thác nước tự nhiên cao hơn 45m đổ ầm vang trên vách đá bazan của miệng núi lửa cổ đã tắt, tạo nên làn sương nước kỳ ảo phản chiếu cầu vồng 7 sắc rực rỡ."
  },
  {
    "id": "LOC_THACK50",
    "locationId": "LOC_THACK50",
    "name": "Thác K50 (Thác Hang Én) - Kon Chư Răng",
    "address": "Khu Bảo tồn Thiên nhiên Kon Chư Răng, Xã Sơn Lang, Huyện K'Bang, Gia Lai",
    "districtId": "D_KBANG",
    "district": "Huyện K'Bang",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.52,
    "lat": 14.52,
    "longitude": 108.61,
    "lng": 108.61,
    "budget": 50000,
    "ticketPrice": 50000,
    "ratingAvg": 5.0,
    "avgRating": 5.0,
    "reviewCount": 18,
    "bestTime": "Mùa khô tháng 1 đến tháng 6",
    "bestTimeOfDay": "Mùa khô tháng 1 đến tháng 6",
    "imageUrl": "https://dulichkbang.com/wp-content/uploads/2021/08/thac-k50-kbang-gia-lai.jpg",
    "imageUrls": [
      "https://dulichkbang.com/wp-content/uploads/2021/08/thac-k50-kbang-gia-lai.jpg",
      "https://media.mia.vn/uploads/blog-du-lich/thac-k50-kham-pha-ve-dep-hoang-so-tuyet-my-giua-dai-ngan-gia-lai-01-1639016335.jpg"
    ],
    "description": "Tuyệt tác thác nước nguyên sinh nằm ẩn mình giữa lõi rừng già Kon Chư Răng. Dòng thác bạc cao hơn 50m buông xõa như dải lụa tiên cảnh giữa vòm hang đá cổ nơi hàng ngàn cánh én trú ngụ."
  },
  {
    "id": "LOC_VQG_KONKAKINH",
    "locationId": "LOC_VQG_KONKAKINH",
    "name": "Vườn Quốc gia Kon Ka Kinh",
    "address": "Xã Ayun, Huyện Mang Yang & K'Bang, Gia Lai",
    "districtId": "D_MANGYANG",
    "district": "Huyện Mang Yang",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.3,
    "lat": 14.3,
    "longitude": 108.4,
    "lng": 108.4,
    "budget": 60000,
    "ticketPrice": 60000,
    "ratingAvg": 4.8,
    "avgRating": 4.8,
    "reviewCount": 18,
    "bestTime": "Mùa khô, thích hợp trekking",
    "bestTimeOfDay": "Mùa khô, thích hợp trekking",
    "imageUrl": "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2020/09/vuon-quoc-gia-kon-ka-kinh.jpg",
    "imageUrls": [
      "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2020/09/vuon-quoc-gia-kon-ka-kinh.jpg",
      "https://gialai.gov.vn/Uploads/Images/2021/kon-ka-kinh.jpg"
    ],
    "description": "Vườn Di sản ASEAN với hệ sinh thái rừng á nhiệt đới phong phú, nơi cư ngụ của loài Voọc chà vá chân xám quý hiếm và đỉnh Kon Ka Kinh cao 1.748m - nóc nhà của tỉnh Gia Lai."
  },
  {
    "id": "LOC_DOICOHONG_DAKDOA",
    "locationId": "LOC_DOICOHONG_DAKDOA",
    "name": "Đồi Cỏ Hồng Đắk Đoa (Rừng thông Glar)",
    "address": "Xã Glar, Huyện Đắk Đoa, Gia Lai",
    "districtId": "D_DAKDOA",
    "district": "Huyện Đắk Đoa",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 13.98,
    "lat": 13.98,
    "longitude": 108.15,
    "lng": 108.15,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Sáng sớm bình minh tháng 11 - 12",
    "bestTimeOfDay": "Sáng sớm bình minh tháng 11 - 12",
    "imageUrl": "https://dulichgialai.gov.vn/uploads/images/doi-co-hong-dak-doa.jpg",
    "imageUrls": [
      "https://dulichgialai.gov.vn/uploads/images/doi-co-hong-dak-doa.jpg",
      "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2020/11/doi-co-hong-glar-dak-doa.jpg"
    ],
    "description": "Thảo nguyên cỏ hồng đuôi chồn bồng bềnh dưới ánh sương mai xen lẫn rừng thông dáng bonsai tự nhiên, tạo nên bức tranh thiên nhiên lãng mạn níu chân du khách."
  },
  {
    "id": "LOC_THAC_HANGDOI",
    "locationId": "LOC_THAC_HANGDOI",
    "name": "Thác Hang Dơi Kbang",
    "address": "Thị trấn Kbang, Huyện K'Bang, Gia Lai",
    "districtId": "D_KBANG",
    "district": "Huyện K'Bang",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.18,
    "lat": 14.18,
    "longitude": 108.6,
    "lng": 108.6,
    "budget": 15000,
    "ticketPrice": 15000,
    "ratingAvg": 4.6,
    "avgRating": 4.6,
    "reviewCount": 18,
    "bestTime": "Buổi sáng",
    "bestTimeOfDay": "Buổi sáng",
    "imageUrl": "https://dulichkbang.com/wp-content/uploads/2021/08/thac-hang-doi-kbang.jpg",
    "imageUrls": [
      "https://dulichkbang.com/wp-content/uploads/2021/08/thac-hang-doi-kbang.jpg",
      "https://media.mia.vn/uploads/blog-du-lich/thac-hang-doi-kbang-gia-lai.jpg"
    ],
    "description": "Thác nước hoang sơ chia làm nhiều tầng đá cuội tự nhiên giữa thung lũng rừng nguyên sinh Kbang, điểm dã ngoại picnic yêu thích của giới phượt thủ."
  },
  {
    "id": "LOC_DINH_CHUNAM",
    "locationId": "LOC_DINH_CHUNAM",
    "name": "Đỉnh Núi Chư Nâm",
    "address": "Xã Chư Đang Ya, Huyện Chư Păh, Gia Lai",
    "districtId": "D_CHUPAH",
    "district": "Huyện Chư Păh",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.16,
    "lat": 14.16,
    "longitude": 108.08,
    "lng": 108.08,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.8,
    "avgRating": 4.8,
    "reviewCount": 18,
    "bestTime": "Sáng sớm săn mây (5h - 7h)",
    "bestTimeOfDay": "Sáng sớm săn mây (5h - 7h)",
    "imageUrl": "https://gialai.info/wp-content/uploads/2022/10/dinh-chu-nam-gia-lai.jpg",
    "imageUrls": [
      "https://gialai.info/wp-content/uploads/2022/10/dinh-chu-nam-gia-lai.jpg",
      "https://media.mia.vn/uploads/blog-du-lich/trekking-dinh-chu-nam-gia-lai.jpg"
    ],
    "description": "Đỉnh núi cao nhất vùng bình nguyên Chư Păh (gần 1.500m), thiên đường săn biển mây bồng bềnh và ngắm toàn cảnh thung lũng miệng núi lửa Chư Đang Ya từ trên cao."
  },
  {
    "id": "LOC_THUYDIEN_IALY",
    "locationId": "LOC_THUYDIEN_IALY",
    "name": "Lòng Hồ Thủy điện Ia Ly",
    "address": "Xã Ia Mơ Nông, Huyện Chư Păh, Gia Lai",
    "districtId": "D_CHUPAH",
    "district": "Huyện Chư Păh",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.215,
    "lat": 14.215,
    "longitude": 107.828,
    "lng": 107.828,
    "budget": 30000,
    "ticketPrice": 30000,
    "ratingAvg": 4.6,
    "avgRating": 4.6,
    "reviewCount": 18,
    "bestTime": "Buổi chiều ngắm hoàng hôn sông Sê San",
    "bestTimeOfDay": "Buổi chiều ngắm hoàng hôn sông Sê San",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/thuy-dien-ia-ly-gia-lai-01-1658483210.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/thuy-dien-ia-ly-gia-lai-01-1658483210.jpg",
      "https://gialai.gov.vn/Uploads/Images/2021/thuy-dien-ia-ly.jpg"
    ],
    "description": "Công trình thủy điện ngầm lớn thứ hai Việt Nam trên dòng sông Sê San hùng vĩ, kết hợp lòng hồ sinh thái mênh mông sông nước giữa điệp trùng đồi núi."
  },
  {
    "id": "LOC_RUNGCAOSU_CHUPAH",
    "locationId": "LOC_RUNGCAOSU_CHUPAH",
    "name": "Rừng Cao su Chư Păh (Mùa thay lá)",
    "address": "Thị trấn Phú Hòa, Huyện Chư Păh, Gia Lai",
    "districtId": "D_CHUPAH",
    "district": "Huyện Chư Păh",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.09,
    "lat": 14.09,
    "longitude": 108.05,
    "lng": 108.05,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Tháng 12 đến tháng 2 (mùa lá đỏ)",
    "bestTimeOfDay": "Tháng 12 đến tháng 2 (mùa lá đỏ)",
    "imageUrl": "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2020/09/rung-cao-su-gia-lai.jpg",
    "imageUrls": [
      "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2020/09/rung-cao-su-gia-lai.jpg",
      "https://gialai.gov.vn/Uploads/Images/2021/11/rung-cao-su-chu-pah.jpg"
    ],
    "description": "Con đường rợp bóng hàng cây cao su thẳng tắp, chuyển sắc từ vàng sang đỏ rực vào mùa rụng lá tạo nên khung cảnh lãng mạn đậm chất điện ảnh."
  },
  {
    "id": "LOC_THAC_BAUCAN",
    "locationId": "LOC_THAC_BAUCAN",
    "name": "Thác Bàu Cạn (Thác Đội 3)",
    "address": "Xã Bàu Cạn, Huyện Chư Prông, Gia Lai",
    "districtId": "D_CHUPRONG",
    "district": "Huyện Chư Prông",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 13.85,
    "lat": 13.85,
    "longitude": 107.98,
    "lng": 107.98,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.5,
    "avgRating": 4.5,
    "reviewCount": 18,
    "bestTime": "Mùa mưa hoặc đầu mùa khô",
    "bestTimeOfDay": "Mùa mưa hoặc đầu mùa khô",
    "imageUrl": "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2021/04/thac-bau-can-chu-prong.jpg",
    "imageUrls": [
      "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2021/04/thac-bau-can-chu-prong.jpg"
    ],
    "description": "Dòng thác thơ mộng nép mình bên cạnh những nương chè Bàu Cạn trăm tuổi xanh ngắt, điểm cắm trại cuối tuần quen thuộc của người dân phố núi."
  },
  {
    "id": "LOC_THAC_IAKREL",
    "locationId": "LOC_THAC_IAKREL",
    "name": "Thác Ia Krel",
    "address": "Xã Ia Krel, Huyện Đức Cơ, Gia Lai",
    "districtId": "D_DUCCO",
    "district": "Huyện Đức Cơ",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 13.78,
    "lat": 13.78,
    "longitude": 107.72,
    "lng": 107.72,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.5,
    "avgRating": 4.5,
    "reviewCount": 18,
    "bestTime": "Ban ngày",
    "bestTimeOfDay": "Ban ngày",
    "imageUrl": "https://dulichgialai.gov.vn/uploads/images/thac-ia-krel.jpg",
    "imageUrls": [
      "https://dulichgialai.gov.vn/uploads/images/thac-ia-krel.jpg"
    ],
    "description": "Dòng thác hoang sơ miền biên giới Đức Cơ với các bãi đá bazan bằng phẳng, thích hợp cho các hoạt động dã ngoại ngoài trời và câu cá thư giãn."
  },
  {
    "id": "LOC_THUYDIEN_SESAN4",
    "locationId": "LOC_THUYDIEN_SESAN4",
    "name": "Hồ Thủy điện Sê San 4",
    "address": "Xã Ia O, Huyện Ia Grai, Gia Lai",
    "districtId": "D_IAGRAI",
    "district": "Huyện Ia Grai",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.02,
    "lat": 14.02,
    "longitude": 107.6,
    "lng": 107.6,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Buổi chiều lộng gió",
    "bestTimeOfDay": "Buổi chiều lộng gió",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/ho-thuy-dien-se-san-4-gia-lai-01-1661917345.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/ho-thuy-dien-se-san-4-gia-lai-01-1661917345.jpg"
    ],
    "description": "Biển hồ nhân tạo giữa đại ngàn Tây Nguyên với làng chài nổi Sê San, nơi du khách có thể trải nghiệm chèo thuyền độc mộc và thưởng thức cá lăng lòng hồ nướng than hồng."
  },
  {
    "id": "LOC_SUOI_DACO_LANGVAN",
    "locationId": "LOC_SUOI_DACO_LANGVAN",
    "name": "Suối Đá Cổ Làng Vân",
    "address": "Làng Vân, Xã Ia Mơ Nông, Huyện Chư Păh, Gia Lai",
    "districtId": "D_CHUPAH",
    "district": "Huyện Chư Păh",
    "categoryId": "CAT_GL_NATURE",
    "category": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "latitude": 14.18,
    "lat": 14.18,
    "longitude": 107.95,
    "lng": 107.95,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.8,
    "avgRating": 4.8,
    "reviewCount": 18,
    "bestTime": "Sáng 9h - 15h",
    "bestTimeOfDay": "Sáng 9h - 15h",
    "imageUrl": "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2021/04/suoi-da-co-lang-van-gia-lai.jpg",
    "imageUrls": [
      "https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2021/04/suoi-da-co-lang-van-gia-lai.jpg"
    ],
    "description": "Quần thể cột đá bazan hình lục lăng kỳ vĩ có cấu trúc tương tự Gành Đá Đĩa, xếp lớp tầng tầng lớp lớp bên bờ suối trong veo giữa buôn làng Jrai nguyên sơ."
  },
  {
    "id": "LOC_NHADAY_PLEIKU",
    "locationId": "LOC_NHADAY_PLEIKU",
    "name": "Di tích Lịch sử Nhà đày Pleiku",
    "address": "Đường Ngô Gia Tự, Phường Hội Thương, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_HISTORY",
    "category": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "latitude": 13.9833,
    "lat": 13.9833,
    "longitude": 108.005,
    "lng": 108.005,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.6,
    "avgRating": 4.6,
    "reviewCount": 18,
    "bestTime": "Giờ hành chính (7h30 - 17h)",
    "bestTimeOfDay": "Giờ hành chính (7h30 - 17h)",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/nha-day-pleiku-chung-nhan-lich-su-hao-hung-cua-pho-nui-01-1658485292.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/nha-day-pleiku-chung-nhan-lich-su-hao-hung-cua-pho-nui-01-1658485292.jpg"
    ],
    "description": "Di tích quốc gia đặc biệt ghi dấu tội ác thực dân Pháp và đế quốc Mỹ, đồng thời tôn vinh ý chí kiên trung bất khuất của các chiến sĩ cách mạng Tây Nguyên."
  },
  {
    "id": "LOC_TAYSON_THUONGDAO",
    "locationId": "LOC_TAYSON_THUONGDAO",
    "name": "Quần thể Di tích Tây Sơn Thượng Đạo",
    "address": "Thị xã An Khê & Huyện K'Bang, Gia Lai",
    "districtId": "D_ANKHE",
    "district": "Thị xã An Khê",
    "categoryId": "CAT_GL_HISTORY",
    "category": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "latitude": 13.978,
    "lat": 13.978,
    "longitude": 108.652,
    "lng": 108.652,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Ban ngày",
    "bestTimeOfDay": "Ban ngày",
    "imageUrl": "https://dulichkbang.com/wp-content/uploads/2022/02/cong-khu-di-tich-tay-son-thuong-dao-an-khe-gia-lai-800x400.jpg",
    "imageUrls": [
      "https://dulichkbang.com/wp-content/uploads/2022/02/cong-khu-di-tich-tay-son-thuong-dao-an-khe-gia-lai-800x400.jpg",
      "https://vstatic.vietnam.vn/vietnam/resource/IMAGE/2025/7/3/b5661274536c4ba4b9999460477570e6"
    ],
    "description": "Căn cứ địa khởi nghĩa của phong trào ba anh em Tây Sơn Tam Kiệt (Nguyễn Nhạc, Nguyễn Huệ, Nguyễn Lữ) năm 1771, gồm Đền An Khê, Gò Chợ, Vườn Mít Cô Hầu."
  },
  {
    "id": "LOC_ROCTUNG_GODA",
    "locationId": "LOC_ROCTUNG_GODA",
    "name": "Di tích Khảo cổ sơ kỳ Đá cũ Rộc Tưng - Gò Đá",
    "address": "Xã Xuân An, Thị xã An Khê, Gia Lai",
    "districtId": "D_ANKHE",
    "district": "Thị xã An Khê",
    "categoryId": "CAT_GL_HISTORY",
    "category": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "latitude": 13.99,
    "lat": 13.99,
    "longitude": 108.68,
    "lng": 108.68,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.8,
    "avgRating": 4.8,
    "reviewCount": 18,
    "bestTime": "Ban ngày",
    "bestTimeOfDay": "Ban ngày",
    "imageUrl": "https://images.vietnamtourism.gov.vn/vn/images/2022/thang_5/2505.gia_lai_an_khe_-_diem_den_hap_dan_du_khach1.jpg",
    "imageUrls": [
      "https://images.vietnamtourism.gov.vn/vn/images/2022/thang_5/2505.gia_lai_an_khe_-_diem_den_hap_dan_du_khach1.jpg"
    ],
    "description": "Di tích khảo cổ học quốc gia đặc biệt chứng minh sự xuất hiện của người tiền sử tại Việt Nam cách đây khoảng 80 vạn năm, một phát hiện có tầm vóc khoa học thế giới."
  },
  {
    "id": "LOC_THAP_BANGKENG",
    "locationId": "LOC_THAP_BANGKENG",
    "name": "Tháp Bang Keng (Phế tích Tháp Chăm)",
    "address": "Xã Krông Năng, Huyện Krông Pa, Gia Lai",
    "districtId": "D_KRONPA",
    "district": "Huyện Krông Pa",
    "categoryId": "CAT_GL_HISTORY",
    "category": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "latitude": 13.25,
    "lat": 13.25,
    "longitude": 108.7,
    "lng": 108.7,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.4,
    "avgRating": 4.4,
    "reviewCount": 18,
    "bestTime": "Sáng mát",
    "bestTimeOfDay": "Sáng mát",
    "imageUrl": "https://gialai.gov.vn/Uploads/Images/2021/thap-bang-keng.jpg",
    "imageUrls": [
      "https://gialai.gov.vn/Uploads/Images/2021/thap-bang-keng.jpg"
    ],
    "description": "Dấu tích kiến trúc văn hóa Chăm Pa cổ xưa trên lưu vực sông Ba ở phía nam Gia Lai, minh chứng sinh động cho giao lưu văn hóa giữa duyên hải và cao nguyên."
  },
  {
    "id": "LOC_LANG_STOR",
    "locationId": "LOC_LANG_STOR",
    "name": "Làng Kháng chiến Stơr (Quê hương Anh hùng Núp)",
    "address": "Xã Tơ Tung, Huyện K'Bang, Gia Lai",
    "districtId": "D_KBANG",
    "district": "Huyện K'Bang",
    "categoryId": "CAT_GL_HISTORY",
    "category": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "latitude": 14.15,
    "lat": 14.15,
    "longitude": 108.52,
    "lng": 108.52,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Ban ngày",
    "bestTimeOfDay": "Ban ngày",
    "imageUrl": "https://dulichkbang.com/wp-content/uploads/2022/03/lang-khang-chien-stor-kbang.jpg",
    "imageUrls": [
      "https://dulichkbang.com/wp-content/uploads/2022/03/lang-khang-chien-stor-kbang.jpg"
    ],
    "description": "Cái nôi kháng chiến của đồng bào Bahnar gắn liền với tên tuổi Anh hùng Đinh Núp trong tác phẩm 'Đất nước đứng lên', lưu giữ nhà lưu niệm và nhà rông truyền thống."
  },
  {
    "id": "LOC_CHIENTHANG_DAKPO",
    "locationId": "LOC_CHIENTHANG_DAKPO",
    "name": "Di tích Lịch sử Chiến thắng Đắk Pơ",
    "address": "Quốc lộ 19, Huyện Đắk Pơ, Gia Lai",
    "districtId": "D_ANKHE",
    "district": "Thị xã An Khê",
    "categoryId": "CAT_GL_HISTORY",
    "category": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "latitude": 13.95,
    "lat": 13.95,
    "longitude": 108.55,
    "lng": 108.55,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.5,
    "avgRating": 4.5,
    "reviewCount": 18,
    "bestTime": "Ban ngày",
    "bestTimeOfDay": "Ban ngày",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/tuong-dai-chien-thang-dak-po-gia-lai.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/tuong-dai-chien-thang-dak-po-gia-lai.jpg"
    ],
    "description": "Tượng đài chiến thắng trận phục kích Đắk Pơ lẫy lừng ngày 24/6/1954 trên Quốc lộ 19, được mệnh danh là 'Điện Biên Phủ ở Liên khu V'."
  },
  {
    "id": "LOC_THUNGLUNG_IADRANG",
    "locationId": "LOC_THUNGLUNG_IADRANG",
    "name": "Di tích Thung lũng Ia Drăng",
    "address": "Xã Ia Me, Huyện Chư Prông, Gia Lai",
    "districtId": "D_CHUPRONG",
    "district": "Huyện Chư Prông",
    "categoryId": "CAT_GL_HISTORY",
    "category": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "latitude": 13.58,
    "lat": 13.58,
    "longitude": 107.75,
    "lng": 107.75,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.4,
    "avgRating": 4.4,
    "reviewCount": 18,
    "bestTime": "Ban ngày",
    "bestTimeOfDay": "Ban ngày",
    "imageUrl": "https://gialai.gov.vn/Uploads/Images/2022/thung-lung-ia-drang.jpg",
    "imageUrls": [
      "https://gialai.gov.vn/Uploads/Images/2022/thung-lung-ia-drang.jpg"
    ],
    "description": "Nơi diễn ra trận chạm trán quy mô lớn đầu tiên giữa quân chủ lực Việt Nam và kỵ binh bay Mỹ vào tháng 11/1965 dưới chân núi Chu Pơr linh thiêng."
  },
  {
    "id": "LOC_MINHTHANH",
    "locationId": "LOC_MINHTHANH",
    "name": "Chùa Minh Thành Pleiku",
    "address": "348 đường Nguyễn Viết Xuân, Phường Hội Phú, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_CULTURE",
    "category": "Văn hóa Dân tộc, Làng nghề & Lễ hội truyền thống",
    "latitude": 13.9667,
    "lat": 13.9667,
    "longitude": 108.0167,
    "lng": 108.0167,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.9,
    "avgRating": 4.9,
    "reviewCount": 18,
    "bestTime": "Sáng 7h - 10h hoặc Hoàng hôn",
    "bestTimeOfDay": "Sáng 7h - 10h hoặc Hoàng hôn",
    "imageUrl": "https://media.gody.vn/images/gia-lai/chua-minh-thanh/11-2016/20161101090033-chua-minh-thanh-gody(3).jpg",
    "imageUrls": [
      "https://media.gody.vn/images/gia-lai/chua-minh-thanh/11-2016/20161101090033-chua-minh-thanh-gody(3).jpg",
      "https://touring.vn/wp-content/uploads/2024/04/Chua-Minh-Thanh-Gia-Lai-13.jpg"
    ],
    "description": "Quần thể kiến trúc Phật giáo tuyệt mỹ mang phong cách Á Đông cổ kính kết hợp tháp Từ Ân 9 tầng thanh tịnh uy nghiêm giữa trung tâm thành phố Pleiku."
  },
  {
    "id": "LOC_LANGVOI",
    "locationId": "LOC_LANGVOI",
    "name": "Làng Văn hóa Du lịch Plei Ốp",
    "address": "Phường Hoa Lư, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_CULTURE",
    "category": "Văn hóa Dân tộc, Làng nghề & Lễ hội truyền thống",
    "latitude": 13.99,
    "lat": 13.99,
    "longitude": 108.01,
    "lng": 108.01,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Buổi chiều tối giao lưu cồng chiêng",
    "bestTimeOfDay": "Buổi chiều tối giao lưu cồng chiêng",
    "imageUrl": "https://cdn.xanhsm.com/2025/03/1b3f9e9b-lang-plei-op-2.jpg",
    "imageUrls": [
      "https://cdn.xanhsm.com/2025/03/1b3f9e9b-lang-plei-op-2.jpg",
      "https://cdn.xanhsm.com/2025/03/6c9ec59a-lang-plei-op-5.jpg"
    ],
    "description": "Buôn làng người Jrai bản địa nguyên sơ nằm ngay lòng đô thị Pleiku, nơi du khách được đắm chìm trong tiếng cồng chiêng, ngắm nhà rông và uống rượu cần ấm áp."
  },
  {
    "id": "LOC_CHUA_BUUMINH",
    "locationId": "LOC_CHUA_BUUMINH",
    "name": "Chùa Bửu Minh",
    "address": "Xã Nghĩa Hưng, Huyện Chư Păh, Gia Lai",
    "districtId": "D_CHUPAH",
    "district": "Huyện Chư Păh",
    "categoryId": "CAT_GL_CULTURE",
    "category": "Văn hóa Dân tộc, Làng nghề & Lễ hội truyền thống",
    "latitude": 14.078,
    "lat": 14.078,
    "longitude": 108.018,
    "lng": 108.018,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.8,
    "avgRating": 4.8,
    "reviewCount": 18,
    "bestTime": "Buổi sáng thanh tịnh",
    "bestTimeOfDay": "Buổi sáng thanh tịnh",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/chua-buu-minh-gia-lai-ve-dep-thanh-tinh-giua-doi-che-01-1658484123.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/chua-buu-minh-gia-lai-ve-dep-thanh-tinh-giua-doi-che-01-1658484123.jpg"
    ],
    "description": "Ngôi cổ tự thanh bình tọa lạc giữa ngút ngàn đồi chè Biển Hồ xanh mướt, nổi bật với đỉnh tháp nhọn vươn cao lên bầu trời xanh bình yên."
  },
  {
    "id": "LOC_NHATHO_PLEICHUET",
    "locationId": "LOC_NHATHO_PLEICHUET",
    "name": "Nhà thờ Gỗ Pleichuet",
    "address": "Đường Trương Định, Phường Thắng Lợi, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_CULTURE",
    "category": "Văn hóa Dân tộc, Làng nghề & Lễ hội truyền thống",
    "latitude": 13.972,
    "lat": 13.972,
    "longitude": 108.028,
    "lng": 108.028,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.7,
    "avgRating": 4.7,
    "reviewCount": 18,
    "bestTime": "Ban ngày",
    "bestTimeOfDay": "Ban ngày",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/nha-tho-pleichuet-kien-truc-nha-rong-tay-nguyen-01-1658486745.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/nha-tho-pleichuet-kien-truc-nha-rong-tay-nguyen-01-1658486745.jpg"
    ],
    "description": "Công trình tôn giáo độc đáo được dựng hoàn toàn theo mô hình nhà rông truyền thống của đồng bào Jrai với mái nhọn cao vút và hoa văn chạm khắc tinh xảo."
  },
  {
    "id": "LOC_LANG_MOHRA",
    "locationId": "LOC_LANG_MOHRA",
    "name": "Làng Du lịch Cộng đồng Mơ Hra - K'Păng",
    "address": "Xã K'Dang, Huyện Đắk Đoa, Gia Lai",
    "districtId": "D_DAKDOA",
    "district": "Huyện Đắk Đoa",
    "categoryId": "CAT_GL_CULTURE",
    "category": "Văn hóa Dân tộc, Làng nghề & Lễ hội truyền thống",
    "latitude": 13.95,
    "lat": 13.95,
    "longitude": 108.2,
    "lng": 108.2,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.6,
    "avgRating": 4.6,
    "reviewCount": 18,
    "bestTime": "Cuối tuần",
    "bestTimeOfDay": "Cuối tuần",
    "imageUrl": "https://dulichgialai.gov.vn/uploads/images/lang-mo-hra-dak-doa.jpg",
    "imageUrls": [
      "https://dulichgialai.gov.vn/uploads/images/lang-mo-hra-dak-doa.jpg"
    ],
    "description": "Điểm du lịch cộng đồng kiểu mẫu của người Bahnar với nghề dệt thổ cẩm truyền thống, tạc tượng gỗ dân gian và những điệu múa xoang nhịp nhàng."
  },
  {
    "id": "LOC_QUANGTRUONG_GL",
    "locationId": "LOC_QUANGTRUONG_GL",
    "name": "Quảng trường Đại Đoàn Kết & Bảo tàng Gia Lai",
    "address": "Đường Trần Hưng Đạo, Phường Tây Sơn, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_PARK",
    "category": "Công viên & Không gian cảnh quan công cộng",
    "latitude": 13.9806,
    "lat": 13.9806,
    "longitude": 108.0067,
    "lng": 108.0067,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.9,
    "avgRating": 4.9,
    "reviewCount": 18,
    "bestTime": "Chiều tối (17h - 22h)",
    "bestTimeOfDay": "Chiều tối (17h - 22h)",
    "imageUrl": "https://vstatic.vietnam.vn/vietnam/resource/IMAGE/2024/11/12/quang-truong-dai-doan-ket.jpg",
    "imageUrls": [
      "https://vstatic.vietnam.vn/vietnam/resource/IMAGE/2024/11/12/quang-truong-dai-doan-ket.jpg",
      "https://media.mia.vn/uploads/blog-du-lich/quang-truong-dai-doan-ket-gia-lai-01-1658482109.jpg"
    ],
    "description": "Trái tim của thành phố Pleiku với Tượng đài Bác Hồ với các dân tộc Tây Nguyên lớn nhất cả nước, bức phù điêu đá tạc hình tượng sử thi và tháp đá mô phỏng cồng chiêng."
  },
  {
    "id": "LOC_CONGVIEN_DIENHONG",
    "locationId": "LOC_CONGVIEN_DIENHONG",
    "name": "Công viên Diên Hồng",
    "address": "Đường Thống Nhất, Phường Ia Kring, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_PARK",
    "category": "Công viên & Không gian cảnh quan công cộng",
    "latitude": 13.975,
    "lat": 13.975,
    "longitude": 107.99,
    "lng": 107.99,
    "budget": 0,
    "ticketPrice": 0,
    "ratingAvg": 4.6,
    "avgRating": 4.6,
    "reviewCount": 18,
    "bestTime": "Sáng sớm hoặc Chiều mát",
    "bestTimeOfDay": "Sáng sớm hoặc Chiều mát",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/cong-vien-dien-hong-gia-lai-01-1658485901.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/cong-vien-dien-hong-gia-lai-01-1658485901.jpg"
    ],
    "description": "Lá phổi xanh giữa lòng đô thị Pleiku với hồ nước trong lành, cầu treo uốn lượn, vườn hoa và những quán cafe ven hồ râm mát cho du khách tản bộ thư giãn."
  },
  {
    "id": "LOC_CONGVIEN_DONGXANH",
    "locationId": "LOC_CONGVIEN_DONGXANH",
    "name": "Công viên Văn hóa Đồng Xanh",
    "address": "Thôn 5, Xã An Phú, TP. Pleiku, Gia Lai",
    "districtId": "D_PLEIKU",
    "district": "Thành phố Pleiku",
    "categoryId": "CAT_GL_PARK",
    "category": "Công viên & Không gian cảnh quan công cộng",
    "latitude": 13.94,
    "lat": 13.94,
    "longitude": 108.06,
    "lng": 108.06,
    "budget": 40000,
    "ticketPrice": 40000,
    "ratingAvg": 4.5,
    "avgRating": 4.5,
    "reviewCount": 18,
    "bestTime": "Ban ngày cuối tuần",
    "bestTimeOfDay": "Ban ngày cuối tuần",
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/cong-vien-dong-xanh-gia-lai-01-1658487890.jpg",
    "imageUrls": [
      "https://media.mia.vn/uploads/blog-du-lich/cong-vien-dong-xanh-gia-lai-01-1658487890.jpg"
    ],
    "description": "Khu sinh thái văn hóa tái hiện thu nhỏ bản sắc Tây Nguyên với nhà mồ, nhà rông, tượng gỗ dân gian, cây hóa thạch triệu năm và cây đàn T'rưng nước độc đáo."
  }
];

export const MOCK_CATEGORIES = [
  {
    "id": "CAT_GL_NATURE",
    "categoryId": "CAT_GL_NATURE",
    "name": "Điểm du lịch sinh thái, danh lam thắng cảnh tự nhiên",
    "description": "Hồ miệng núi lửa cổ, thác nước nguyên sinh, đồi chè, rừng thông và các vườn quốc gia bảo tồn thiên nhiên",
    "icon": "Trees"
  },
  {
    "id": "CAT_GL_HISTORY",
    "categoryId": "CAT_GL_HISTORY",
    "name": "Di tích Lịch sử - Văn hóa - Khảo cổ",
    "description": "Hệ thống di tích lịch sử cách mạng, di chỉ khảo cổ học đồ đá cũ và căn cứ khởi nghĩa Tây Sơn Thượng Đạo",
    "icon": "Landmark"
  },
  {
    "id": "CAT_GL_CULTURE",
    "categoryId": "CAT_GL_CULTURE",
    "name": "Văn hóa Dân tộc, Làng nghề & Lễ hội truyền thống",
    "description": "Không gian văn hóa cồng chiêng Jrai/Bahnar, làng nghề dệt thổ cẩm, kiến trúc nhà rông và chùa tháp cổ",
    "icon": "Users"
  },
  {
    "id": "CAT_GL_PARK",
    "categoryId": "CAT_GL_PARK",
    "name": "Công viên & Không gian cảnh quan công cộng",
    "description": "Quảng trường văn hóa, công viên sinh thái đô thị và các không gian cảnh quan sinh hoạt cộng đồng",
    "icon": "Sun"
  }
];

export const MOCK_DISTRICTS = [
  {
    "id": "D_PLEIKU",
    "districtId": "D_PLEIKU",
    "name": "Thành phố Pleiku",
    "locationCount": 8
  },
  {
    "id": "D_CHUPAH",
    "districtId": "D_CHUPAH",
    "name": "Huyện Chư Păh",
    "locationCount": 7
  },
  {
    "id": "D_CHUSE",
    "districtId": "D_CHUSE",
    "name": "Huyện Chư Sê",
    "locationCount": 1
  },
  {
    "id": "D_DAKDOA",
    "districtId": "D_DAKDOA",
    "name": "Huyện Đắk Đoa",
    "locationCount": 2
  },
  {
    "id": "D_KBANG",
    "districtId": "D_KBANG",
    "name": "Huyện K'Bang",
    "locationCount": 3
  },
  {
    "id": "D_MANGYANG",
    "districtId": "D_MANGYANG",
    "name": "Huyện Mang Yang",
    "locationCount": 1
  },
  {
    "id": "D_ANKHE",
    "districtId": "D_ANKHE",
    "name": "Thị xã An Khê",
    "locationCount": 3
  },
  {
    "id": "D_IAGRAI",
    "districtId": "D_IAGRAI",
    "name": "Huyện Ia Grai",
    "locationCount": 1
  },
  {
    "id": "D_CHUPRONG",
    "districtId": "D_CHUPRONG",
    "name": "Huyện Chư Prông",
    "locationCount": 2
  },
  {
    "id": "D_DUCCO",
    "districtId": "D_DUCCO",
    "name": "Huyện Đức Cơ",
    "locationCount": 1
  },
  {
    "id": "D_KRONPA",
    "districtId": "D_KRONPA",
    "name": "Huyện Krông Pa",
    "locationCount": 1
  }
];

export const MOCK_DISHES = [
  {
    "id": "DISH_PHOKHO",
    "name": "Phở Khô Hai Tô Gia Lai",
    "description": "Món ăn danh bất hư truyền của Gia Lai: một tô sợi phở trụng trộn sốt tương nâu ngọt đậm đà kèm thịt bằm, một tô nước dùng xương bò thơm ngát hành hoa.",
    "priceRange": "40.000đ - 65.000đ / tô",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800"
  },
  {
    "id": "DISH_GANUONG_COMLAM",
    "name": "Gà Nướng Sa Lửa & Cơm Lam Ống Tre",
    "description": "Gà thả đồi ướp lá rừng kẹp thanh tre nướng sa lửa than hồng rực rỡ, thịt săn ngọt thơm ăn cùng cơm nếp nương nướng trong ống tre dẻo bùi.",
    "priceRange": "220.000đ - 300.000đ / con",
    "rating": 4.8,
    "imageUrl": "https://media.mia.vn/uploads/blog-du-lich/ga-nuong-com-lam-pleiku-01-1658488920.jpg"
  },
  {
    "id": "DISH_BOMOTNANG",
    "name": "Bò Một Nắng Krông Pa Chấm Muối Kiến Vàng",
    "description": "Thịt bò thưng mềm ngọt phơi đúng một mạt nắng gắt Krông Pa, nướng sơ trên than hồng rồi chấm muối làm từ ổ kiến vàng chua cay ngất ngây.",
    "priceRange": "550.000đ - 650.000đ / kg",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800"
  },
  {
    "id": "DISH_BUNCUATHOI",
    "name": "Bún Mắm Cua (Bún Cua Thối Pleiku)",
    "description": "Món ăn kén người nhưng gây nghiện tột bậc của phố núi: cua đồng ủ lên men chua nồng, chan nước dùng đậm vị ăn kèm da heo chiên giòn rụm và măng chua le.",
    "priceRange": "20.000đ - 35.000đ / tô",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800"
  },
  {
    "id": "DISH_CAFE_PLEIKU",
    "name": "Cà Phê Nguyên Chất Pleiku",
    "description": "Ly cà phê đen sánh nâu cánh gián pha phin từ hạt Robusta trồng trên đất bazan núi lửa nồng nàn thơm quyến rũ, nét văn hóa thưởng thức bất hủ của người Pleiku.",
    "priceRange": "25.000đ - 55.000đ / ly",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800"
  },
  {
    "id": "DISH_RUOUCAN",
    "name": "Rượu Cần Men Lá Rừng Bahnar / Jrai",
    "description": "Rượu ủ từ nếp cẩm và men lá cây rừng tự nhiên, uống bằng cần tre vít cong, vị ngọt ấm nồng gắn kết tình cảm anh em du khách.",
    "priceRange": "150.000đ - 250.000đ / chóe",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800"
  }
];

export const MOCK_STAYS = [
  {
    "id": "STAY_HAGL",
    "name": "Khách sạn Hoàng Anh Gia Lai (HAGL Hotel)",
    "type": "Khách sạn 4 sao",
    "address": "01 đường Phù Đổng, TP. Pleiku, Gia Lai",
    "priceRange": "1.200.000đ - 2.500.000đ",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"
  },
  {
    "id": "STAY_BOSTON",
    "name": "Boston Hotel Pleiku",
    "type": "Khách sạn 3 sao",
    "address": "212 đường Sư Vạn Hạnh, Phường Hội Thương, TP. Pleiku, Gia Lai",
    "priceRange": "650.000đ - 1.100.000đ",
    "rating": 4.7,
    "imageUrl": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"
  },
  {
    "id": "STAY_TREXANH",
    "name": "Khách sạn Tre Xanh Plaza",
    "type": "Khách sạn 3 sao",
    "address": "18 đường Lê Lai, Phường Tây Sơn, TP. Pleiku, Gia Lai",
    "priceRange": "500.000đ - 900.000đ",
    "rating": 4.5,
    "imageUrl": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800"
  },
  {
    "id": "STAY_TIENSON",
    "name": "Tiên Sơn Homestay Biển Hồ",
    "type": "Homestay",
    "address": "Xã Tân Sơn, TP. Pleiku (Gần Biển Hồ T'Nưng)",
    "priceRange": "350.000đ - 700.000đ",
    "rating": 4.9,
    "imageUrl": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"
  },
  {
    "id": "STAY_XOM",
    "name": "Xóm Organic Farmstay Chư Păh",
    "type": "Farmstay Sinh thái",
    "address": "Thôn Tiên Sơn 1, Xã Nghĩa Hưng, Huyện Chư Păh, Gia Lai",
    "priceRange": "450.000đ - 850.000đ",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800"
  },
  {
    "id": "STAY_KBANG_ECO",
    "name": "Kbang Eco Homestay & Trekking Base",
    "type": "Homestay",
    "address": "Thị trấn Kbang, Huyện K'Bang, Gia Lai",
    "priceRange": "300.000đ - 600.000đ",
    "rating": 4.8,
    "imageUrl": "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800"
  }
];
